### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [jnralexandre/fundatec#3]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

Tudo ok.

**Nota:** 10! Parabéns 🥳 

# Comentários

https://github.com/jnralexandre/fundatec/blob/75ca8f5c358080c000b17d9fe02fa3c4ba26a318/primeiro-modulo/desenvolvimento-web/exercicios-para-entrega/exercicio-0.5.1/concluidas.html#L12-L16

https://github.com/jnralexandre/fundatec/blob/75ca8f5c358080c000b17d9fe02fa3c4ba26a318/primeiro-modulo/desenvolvimento-web/exercicios-para-entrega/exercicio-0.5.1/concluidas.html#L19-L24

Tanto para os itens de nevegação quando para as tarefas existe uma listagem de itens sendo feita. Para tornar o seu código HTML mais semântico você poderia fazer uso das tags `ul` e `li` e aplicar a remoção dos estilos da listagem através do CSS.

https://github.com/jnralexandre/fundatec/blob/75ca8f5c358080c000b17d9fe02fa3c4ba26a318/primeiro-modulo/desenvolvimento-web/exercicios-para-entrega/exercicio-0.5.1/concluidas.css#L1-L29

Muito do seu CSS é duplicado entre as páginas, com modificação de algumas propriedades como as propriedades de cores.  Existe formas de reaproveitar esses estilos "fixos" e trabalhar com a adição dos estilos diferentes com o uso de classes mais especializadas. Veja abaixo um exemplo.

```css
.tarefas {
    border-style: solid;
    border-width: 3px;
    border-radius: 5px;
    padding: 15px;
    text-align: left;
    transition: transform 0.3s linear;
}
.tarefa__concluida {
    border-color: #0CA789;
}
.tarefa__pendente {
    border-color: #8FD14F;
}
```

No HTML basta fazer uso de duas classes. 

```html
<p class="tarefas tarefa__concluida">Desenvolvimento Web I - Entrega - Exercício - 0.4.1</p>
```
